<?php

// Kenya Counties -> Sub-Counties -> Wards
// Source: IEBC-based dataset (alvinchesaro/Kenya-Counties-SubCounties-and-Wards)
// STATUS: 25 of 47 counties populated (coastal, north eastern, eastern, central,
// and part of Rift Valley). Remaining counties (rest of Rift Valley, Western,
// Nyanza, Nairobi) still need to be added -- see accompanying chat message.
return [
    'Mombasa' => [
        'Changamwe' => [
            'Port Reitz',
            'Kipevu',
            'Airport',
            'Changamwe',
            'Chaani',
        ],
        'Jomvu' => [
            'Jomvu Kuu',
            'Miritini',
            'Mikindani',
        ],
        'Kisauni' => [
            'Mjambere',
            'Junda',
            'Bamburi',
            'Mwakirunge',
            'Mtopanga',
            'Magogoni',
            'Shanzu',
        ],
        'Nyali' => [
            'Frere Town',
            'Ziwa La Ng\'Ombe',
            'Mkomani',
            'Kongowea',
            'Kadzandani',
        ],
        'Likoni' => [
            'Mtongwe',
            'Shika Adabu',
            'Bofu',
            'Likoni',
            'Timbwani',
        ],
        'Mvita' => [
            'Mji Wa Kale/Makadara',
            'Tudor',
            'Tononoka',
            'Shimanzi/Ganjoni',
            'Majengo',
        ],
    ],

    'Kwale' => [
        'Msambweni' => [
            'Gombato Bongwe',
            'Ukunda',
            'Kinondo',
            'Ramisi',
        ],
        'Lungalunga' => [
            'Pongwe/Kikoneni',
            'Dzombo',
            'Mwereni',
            'Vanga',
        ],
        'Matuga' => [
            'Tsimba Golini',
            'Waa',
            'Tiwi',
            'Kubo South',
            'Mkongani',
        ],
        'Kinango' => [
            'Ndavaya',
            'Puma',
            'Kinango',
            'Mackinnon Road',
            'Chengoni/Samburu',
            'Mwavumbo',
            'Kasemeni',
        ],
    ],

    'Kilifi' => [
        'Kilifi North' => [
            'Tezo',
            'Sokoni',
            'Kibarani',
            'Dabaso',
            'Matsangoni',
            'Watamu',
            'Mnarani',
        ],
        'Kilifi South' => [
            'Junju',
            'Mwarakaya',
            'Shimo La Tewa',
            'Chasimba',
            'Mtepeni',
        ],
        'Kaloleni' => [
            'Mariakani',
            'Kayafungo',
            'Kaloleni',
            'Mwanamwinga',
        ],
        'Rabai' => [
            'Mwawesa',
            'Ruruma',
            'Kambe/Ribe',
            'Rabai/Kisurutini',
        ],
        'Ganze' => [
            'Ganze',
            'Bamba',
            'Jaribuni',
            'Sokoke',
        ],
        'Malindi' => [
            'Jilore',
            'Kakuyuni',
            'Ganda',
            'Malindi Town',
            'Shella',
        ],
        'Magarini' => [
            'Marafa',
            'Magarini',
            'Gongoni',
            'Adu',
            'Garashi',
            'Sabaki',
        ],
    ],

    'Tana River' => [
        'Garsen' => [
            'Kipini East',
            'Garsen South',
            'Kipini West',
            'Garsen Central',
            'Garsen West',
            'Garsen North',
        ],
        'Galole' => [
            'Kinakomba',
            'Mikinduni',
            'Chewani',
            'Wayu',
        ],
        'Bura' => [
            'Chewele',
            'Hirimani',
            'Bangale',
            'Sala',
            'Madogo',
        ],
    ],

    'Lamu' => [
        'Lamu East' => [
            'Faza',
            'Kiunga',
            'Basuba',
        ],
        'Lamu West' => [
            'Shella',
            'Mkomani',
            'Hindi',
            'Mkunumbi',
            'Hongwe',
            'Witu',
            'Bahari',
        ],
    ],

    'Taita Taveta' => [
        'Taveta' => [
            'Chala',
            'Mahoo',
            'Bomani',
            'Mboghoni',
            'Mata',
        ],
        'Wundanyi' => [
            'Wundanyi/Mbale',
            'Werugha',
            'Wumingu/Kishushe',
            'Mwanda/Mgange',
        ],
        'Mwatate' => [
            'Rong\'E',
            'Mwatate',
            'Bura',
            'Chawia',
            'Wusi/Kishamba',
        ],
        'Voi' => [
            'Mbololo',
            'Sagalla',
            'Kaloleni',
            'Marungu',
            'Kasigau',
            'Ngolia',
        ],
    ],

    'Garissa' => [
        'Garissa Township' => [
            'Waberi',
            'Galbet',
            'Township',
            'Iftin',
        ],
        'Balambala' => [
            'Balambala',
            'Danyere',
            'Jara Jara',
            'Saka',
            'Sankuri',
        ],
        'Lagdera' => [
            'Modogashe',
            'Benane',
            'Goreale',
            'Maalimin',
            'Sabena',
            'Baraki',
        ],
        'Dadaab' => [
            'Dertu',
            'Dadaab',
            'Labasigale',
            'Damajale',
            'Liboi',
            'Abakaile',
        ],
        'Fafi' => [
            'Bura',
            'Dekaharia',
            'Jarajila',
            'Fafi',
            'Nanighi',
        ],
        'Ijara' => [
            'Hulugho',
            'Sangailu',
            'Ijara',
            'Masalani',
        ],
    ],

    'Wajir' => [
        'Wajir North' => [
            'Gurar',
            'Bute',
            'Korondile',
            'Malkagufu',
            'Batalu',
            'Danaba',
            'Godoma',
        ],
        'Wajir East' => [
            'Wagberi',
            'Township',
            'Barwago',
            'Khorof/Harar',
        ],
        'Tarbaj' => [
            'Elben',
            'Sarman',
            'Tarbaj',
            'Wargadud',
        ],
        'Wajir West' => [
            'Arbajahan',
            'Hadado/Athibohol',
            'Adamasajide',
            'Ganyure/Wagalla',
        ],
        'Eldas' => [
            'Eldas',
            'Della',
            'Lakoley South/Basir',
            'Elnur/Tula Tula',
        ],
        'Wajir South' => [
            'Benane',
            'Burder',
            'Dadaja Bulla',
            'Habasswein',
            'Lagboghol South',
            'Ibrahim Ure',
            'Diif',
        ],
    ],

    'Mandera' => [
        'Mandera West' => [
            'Takaba South',
            'Takaba',
            'Lagsure',
            'Dandu',
            'Gither',
        ],
        'Banissa' => [
            'Banissa',
            'Derkhale',
            'Guba',
            'Malkamari',
            'Kiliwehiri',
        ],
        'Mandera North' => [
            'Ashabito',
            'Guticha',
            'Morothile',
            'Rhamu',
            'Rhamu-Dimtu',
        ],
        'Mandera South' => [
            'Wargadud',
            'Kutulo',
            'Elwak South',
            'Elwak North',
            'Shimbir Fatuma',
        ],
        'Mandera East' => [
            'Arabia',
            'Township',
            'Neboi',
            'Khalalio',
            'Libehia',
        ],
        'Lafey' => [
            'Sala',
            'Fino',
            'Lafey',
            'Waranqara',
            'Alango Gof',
        ],
    ],

    'Marsabit' => [
        'Moyale' => [
            'Butiye',
            'Sololo',
            'Heillu/Manyatta',
            'Golbo',
            'Moyale Township',
            'Uran',
            'Obbu',
        ],
        'North Horr' => [
            'Dukana',
            'Maikona',
            'Turbi',
            'North Horr',
            'Illeret',
        ],
        'Saku' => [
            'Sagante/Jaldessa',
            'Karare',
            'Marsabit Central',
        ],
        'Laisamis' => [
            'Loiyangalani',
            'Kargi/South Horr',
            'Korr/Ngurunit',
            'Logo Logo',
            'Laisamis',
        ],
    ],

    'Isiolo' => [
        'Isiolo North' => [
            'Wabera',
            'Bulla Pesa',
            'Chari',
            'Cherab',
            'Ngare Mara',
            'Burat',
            'Oldo/Nyiro',
        ],
        'Isiolo South' => [
            'Garbatulla',
            'Kinna',
            'Sericho',
        ],
    ],

    'Meru' => [
        'Igembe South' => [
            'Maua',
            'Kiegoi/Antubochiu',
            'Athiru Gaiti',
            'Akachiu',
            'Kanuni',
        ],
        'Igembe Central' => [
            'Akirang\'Ondu',
            'Athiru Ruujine',
            'Igembe East',
            'Njia',
            'Kangeta',
        ],
        'Igembe North' => [
            'Antuambui',
            'Ntunene',
            'Antubetwe Kiongo',
            'Naathu',
            'Amwathi',
        ],
        'Tigania West' => [
            'Athwana',
            'Akithii',
            'Kianjai',
            'Nkomo',
            'Mbeu',
        ],
        'Tigania East' => [
            'Thangatha',
            'Mikinduri',
            'Kiguchwa',
            'Muthara',
            'Karama',
        ],
        'North Imenti' => [
            'Municipality',
            'Ntima East',
            'Ntima West',
            'Nyaki West',
            'Nyaki East',
        ],
        'Buuri' => [
            'Timau',
            'Kisima',
            'Kiirua/Naari',
            'Ruiri/Rwarera',
            'Kibirichia',
        ],
        'Central Imenti' => [
            'Mwang\'Anthia',
            'Abothuguchi Central',
            'Abothuguchi West',
            'Kiagu',
        ],
        'South Imenti' => [
            'Mitunguu',
            'Igoji East',
            'Igoji West',
            'Abogeta East',
            'Abogeta West',
            'Nkuene',
        ],
    ],

    'Tharaka-Nithi' => [
        'Maara' => [
            'Mitheru',
            'Muthambi',
            'Mwimbi',
            'Ganga',
            'Chogoria',
        ],
        'Chuka/Igambang\'ombe' => [
            'Mariani',
            'Karingani',
            'Magumoni',
            'Mugwe',
            'Igambang\'ombe',
        ],
        'Tharaka' => [
            'Gatunga',
            'Mukothima',
            'Nkondi',
            'Chiakariga',
            'Marimanti',
        ],
    ],

    'Embu' => [
        'Manyatta' => [
            'Ruguru/Ngandori',
            'Kithimu',
            'Nginda',
            'Mbeti North',
            'Kirimari',
            'Gaturi South',
        ],
        'Runyenjes' => [
            'Gaturi North',
            'Kagaari South',
            'Central Ward',
            'Kagaari North',
            'Kyeni North',
            'Kyeni South',
        ],
        'Mbeere South' => [
            'Mwea',
            'Makima',
            'Mbeti South',
            'Mavuria',
            'Kiambere',
        ],
        'Mbeere North' => [
            'Nthawa',
            'Muminji',
            'Evurore',
        ],
    ],

    'Kitui' => [
        'Mwingi North' => [
            'Ngomeni',
            'Kyuso',
            'Mumoni',
            'Tseikuru',
            'Tharaka',
        ],
        'Mwingi West' => [
            'Kyome/Thaana',
            'Nguutani',
            'Migwani',
            'Kiomo/Kyethani',
        ],
        'Mwingi Central' => [
            'Central',
            'Kivou',
            'Nguni',
            'Nuu',
            'Mui',
            'Waita',
        ],
        'Kitui West' => [
            'Mutonguni',
            'Kauwi',
            'Matinyani',
            'Kwa Mutonga/Kithumula',
        ],
        'Kitui Rural' => [
            'Kisasi',
            'Mbitini',
            'Kavonza/Yatta',
            'Kanyangi',
        ],
        'Kitui Central' => [
            'Miambani',
            'Township',
            'Kyangwithya West',
            'Mulango',
            'Kyangwithya East',
        ],
        'Kitui East' => [
            'Zombe/Mwitika',
            'Nzambani',
            'Chuluni',
            'Voo/Kyamatu',
            'Endau/Malalani',
            'Mutito/Kaliku',
        ],
        'Kitui South' => [
            'Ikanga/Kyatune',
            'Mutomo',
            'Mutha',
            'Ikutha',
            'Kanziko',
            'Athi',
        ],
    ],

    'Machakos' => [
        'Masinga' => [
            'Kivaa',
            'Masinga Central',
            'Ekalakala',
            'Muthesya',
            'Ndithini',
        ],
        'Yatta' => [
            'Ndalani',
            'Matuu',
            'Kithimani',
            'Ikombe',
            'Katangi',
        ],
        'Kangundo' => [
            'Kangundo North',
            'Kangundo Central',
            'Kangundo East',
            'Kangundo West',
        ],
        'Matungulu' => [
            'Tala',
            'Matungulu North',
            'Matungulu East',
            'Matungulu West',
            'Kyeleni',
        ],
        'Kathiani' => [
            'Mitaboni',
            'Kathiani Central',
            'Upper Kaewa/Iveti',
            'Lower Kaewa/Kaani',
        ],
        'Mavoko' => [
            'Athi River',
            'Kinanie',
            'Muthwani',
            'Syokimau/Mulolongo',
        ],
        'Machakos Town' => [
            'Kalama',
            'Mua',
            'Mutituni',
            'Machakos Central',
            'Mumbuni North',
            'Muvuti/Kiima-Kimwe',
            'Kola',
        ],
        'Mwala' => [
            'Mbiuni',
            'Makutano/Mwala',
            'Masii',
            'Muthetheni',
            'Wamunyu',
            'Kibauni',
        ],
    ],

    'Makueni' => [
        'Mbooni' => [
            'Tulimani',
            'Mbooni',
            'Kithungo/Kitundu',
            'Kiteta/Kisau',
            'Waia-Kako',
            'Kalawa',
        ],
        'Kilome' => [
            'Kasikeu',
            'Mukaa',
            'Kiima Kiu/Kalanzoni',
        ],
        'Kaiti' => [
            'Ukia',
            'Kee',
            'Kilungu',
            'Ilima',
        ],
        'Makueni' => [
            'Wote',
            'Muvau/Kikuumini',
            'Mavindini',
            'Kitise/Kithuki',
            'Kathonzweni',
            'Nzaui/Kilili/Kalamba',
            'Mbitini',
        ],
        'Kibwezi West' => [
            'Makindu',
            'Nguumo',
            'Kikumbulyu North',
            'Kikumbulyu South',
            'Nguu/Masumba',
            'Emali/Mulala',
        ],
        'Kibwezi East' => [
            'Masongaleni',
            'Mtito Andei',
            'Thange',
            'Ivingoni/Nzambani',
        ],
    ],

    'Nyandarua' => [
        'Kinangop' => [
            'Engineer',
            'Gathara',
            'North Kinangop',
            'Murungaru',
            'Njabini/Kiburu',
            'Nyakio',
            'Githabai',
            'Magumu',
        ],
        'Kipipiri' => [
            'Wanjohi',
            'Kipipiri',
            'Geta',
            'Githioro',
        ],
        'Ol Kalou' => [
            'Karau',
            'Kanjuiri Range',
            'Mirangine',
            'Kaimbaga',
            'Rurii',
        ],
        'Ol Jorok' => [
            'Gathanji',
            'Gatimu',
            'Weru',
            'Charagita',
        ],
        'Ndaragwa' => [
            'Leshau/Pondo',
            'Kiriita',
            'Central',
            'Shamata',
        ],
    ],

    'Nyeri' => [
        'Tetu' => [
            'Dedan Kimanthi',
            'Wamagana',
            'Aguthi-Gaaki',
        ],
        'Kieni' => [
            'Mweiga',
            'Naromoru Kiamathaga',
            'Mwiyogo/Endarasha',
            'Mugunda',
            'Gatarakwa',
            'Thegu River',
            'Kabaru',
            'Gakawa',
        ],
        'Mathira' => [
            'Ruguru',
            'Magutu',
            'Iraini',
            'Konyu',
            'Kirimukuyu',
            'Karatina Town',
        ],
        'Othaya' => [
            'Mahiga',
            'Iria-Ini',
            'Chinga',
            'Karima',
        ],
        'Mukurweini' => [
            'Gikondi',
            'Rugi',
            'Mukurwe-Ini West',
            'Mukurwe-Ini Central',
        ],
        'Nyeri Town' => [
            'Kiganjo/Mathari',
            'Rware',
            'Gatitu/Muruguru',
            'Ruring\'U',
            'Kamakwa/Mukaro',
        ],
    ],

    'Kirinyaga' => [
        'Mwea' => [
            'Mutithi',
            'Kangai',
            'Thiba',
            'Wamumu',
            'Nyangati',
            'Murinduko',
            'Gathigiriri',
            'Tebere',
        ],
        'Gichugu' => [
            'Kabare',
            'Baragwi',
            'Njukiini',
            'Ngariama',
            'Karumandi',
        ],
        'Ndia' => [
            'Mukure',
            'Kiine',
            'Kariti',
        ],
        'Kirinyaga Central' => [
            'Mutira',
            'Kanyekini',
            'Kerugoya',
            'Inoi',
        ],
    ],

    'Murang\'a' => [
        'Kangema' => [
            'Kanyenya-Ini',
            'Muguru',
            'Rwathia',
        ],
        'Mathioya' => [
            'Gitugi',
            'Kiru',
            'Kamacharia',
        ],
        'Kiharu' => [
            'Wangu',
            'Mugoiri',
            'Mbiri',
            'Township',
            'Murarandia',
            'Gaturi',
        ],
        'Kigumo' => [
            'Kahumbu',
            'Muthithi',
            'Kigumo',
            'Kangari',
            'Kinyona',
        ],
        'Maragwa' => [
            'Kimorori/Wempa',
            'Makuyu',
            'Kambiti',
            'Kamahuha',
            'Ichagaki',
            'Nginda',
        ],
        'Kandara' => [
            'Ng\'Araria',
            'Muruka',
            'Kagundu-Ini',
            'Gaichanjiru',
            'Ithiru',
            'Ruchu',
        ],
        'Gatanga' => [
            'Ithanga',
            'Kakuzi/Mitubiri',
            'Mugumo-Ini',
            'Kihumbu-Ini',
            'Gatanga',
            'Kariara',
        ],
    ],

    'Kiambu' => [
        'Gatundu South' => [
            'Kiamwangi',
            'Kiganjo',
            'Ndarugu',
            'Ngenda',
        ],
        'Gatundu North' => [
            'Gituamba',
            'Githobokoni',
            'Chania',
            'Mang\'U',
        ],
        'Juja' => [
            'Murera',
            'Theta',
            'Juja',
            'Witeithie',
            'Kalimoni',
        ],
        'Thika Town' => [
            'Township',
            'Kamenu',
            'Hospital',
            'Gatuanyaga',
            'Ngoliba',
        ],
        'Ruiru' => [
            'Gitothua',
            'Biashara',
            'Gatongora',
            'Kahawa Sukari',
            'Kahawa Wendani',
            'Kiuu',
            'Mwiki',
            'Mwihoko',
        ],
        'Githunguri' => [
            'Githunguri',
            'Githiga',
            'Ikinu',
            'Ngewa',
            'Komothai',
        ],
        'Kiambu' => [
            'Ting\'Ang\'A',
            'Ndumberi',
            'Riabai',
            'Township',
        ],
        'Kiambaa' => [
            'Cianda',
            'Karuri',
            'Ndenderu',
            'Muchatha',
            'Kihara',
        ],
        'Kabete' => [
            'Gitaru',
            'Muguga',
            'Nyadhuna',
            'Kabete',
            'Uthiru',
        ],
        'Kikuyu' => [
            'Karai',
            'Nachu',
            'Sigona',
            'Kikuyu',
            'Kinoo',
        ],
        'Limuru' => [
            'Bibirioni',
            'Limuru Central',
            'Ndeiya',
            'Limuru East',
            'Ngecha Tigoni',
        ],
        'Lari' => [
            'Kinale',
            'Kijabe',
            'Nyanduma',
            'Kamburu',
            'Lari/Kirenga',
        ],
    ],

    'Turkana' => [
        'Turkana North' => [
            'Kaeris',
            'Lake Zone',
            'Lapur',
            'Kaaleng/Kaikor',
            'Kibish',
            'Nakalale',
        ],
        'Turkana West' => [
            'Kakuma',
            'Lopur',
            'Letea',
            'Songot',
            'Kalobeyei',
            'Lokichoggio',
        ],
        'Turkana Central' => [
            'Kang\'Atotha',
            'Lodwar Township',
            'Kanamkemer',
        ],
        'Turkana East' => [
            'Kolobia',
            'Kapedo/Napeitom',
        ],
        'Turkana South' => [
            'Kalapata',
            'Katilu',
            'Lokichar',
        ],
        'Loima' => [
            'Loima',
            'Lokiriama/Lorengai',
            'Kotaruk/Lorengai',
            'Kerio Delta',
        ],
    ],

    'West Pokot' => [
        'Kapenguria' => [
            'Siyoi',
            'Riwo',
            'Municipality',
            'Endugh',
        ],
        'Sigor' => [
            'Masol',
            'Sekerr',
            'Lomuke',
            'Weiwei',
        ],
        'Kacheliba' => [
            'Suam',
            'Kasei',
            'Konyao',
            'Kacheliba',
            'Chepareria',
        ],
        'Pokot South' => [
            'Batei',
            'Lombeh',
            'Chepkorio',
        ],
    ],

    'Samburu' => [
        'Samburu West' => [
            'Lodokejek',
            'Suguta Marmar',
            'Maralal',
            'Poro',
            'Loosuk',
        ],
        'Samburu North' => [
            'Elbarta',
            'Nachola',
            'Nyiro',
            'Ndoto',
        ],
        'Samburu East' => [
            'Waso',
            'Wamba East',
            'Wamba West',
            'Wamba North',
        ],
    ],

    // TODO: Trans Nzoia, Uasin Gishu, Elgeyo Marakwet, Nandi, Baringo, Laikipia,
    // Nakuru, Narok, Kajiado, Kericho, Bomet, Kakamega, Vihiga, Bungoma, Busia,
    // Siaya, Kisumu, Homa Bay, Migori, Kisii, Nyamira, Nairobi
];
