<?php

// Kenya's officially recognized ethnic groups / nationalities.
// Source: 2019 Kenya Population and Housing Census, Volume IV
// (Kenya National Bureau of Statistics - knbs.or.ke), sorted alphabetically.
// "Other" appended for self-identifications not captured in the 46 census categories.
return [
    'Aweer',
    'Bajuni',
    'Borana',
    'Burji',
    'Dahalo',
    'Dasenach',
    'Dorobo',
    'El Molo',
    'Embu',
    'Gabra',
    'Gosha',
    'Kalenjin',
    'Kamba',
    'Kenyan American',
    'Kenyan Arabs',
    'Kenyan Asians',
    'Kenyan European',
    'Kenyan (So Stated)',
    'Kikuyu',
    'Kisii',
    'Konso',
    'Kuria',
    'Luhya',
    'Luo',
    'Maasai',
    'Makonde',
    'Mbeere',
    'Meru',
    'Mijikenda',
    'Njemps',
    'Nubi',
    'Orma',
    'Pokomo',
    'Rendile',
    'Sakuye',
    'Samburu',
    'Somali',
    'Suba',
    'Swahili',
    'Taita',
    'Taveta',
    'Teso',
    'Tharaka',
    'Turkana',
    'Walwana',
    'Wayyu',
    'Other',
];
